### ISSUE TITLE
adding stylistic and coverage components to the workflow

### ISSUE THREAD

**Issue by IndrajeetPatil** [jdblischak/r-project-workflows#2]
Maybe these are worth adding to the list?

- `styler`: https://github.com/r-lib/styler
- `gramr`: https://github.com/ropenscilabs/gramr
- `roxygen2`: https://github.com/klutometis/roxygen 
- `covr`: https://github.com/r-lib/covr
- `covrpage`: https://github.com/yonicd/covrpage

**Comment by jdblischak** [comment]
@IndrajeetPatil Thanks for your interest in my repository and for your suggestions! I have set a broad definition for "data analysis workflow" to include any of the following activities: 1) file organization, 2) dependency management (e.g. like GNU Make), or 3) report generation. Based on these criteria, I don't think any of these packages fit very well. The closet is covrpage, which does generate a report, but it's a report of unit tests, not of a data analysis that was performed.

I think roxygen2, covr, and covrpage are best categorized as "R software development tools", for example as catalogued in the section [R Development](https://github.com/qinwf/awesome-R#r-development) of the meta-list [Awesome-R](https://github.com/qinwf/awesome-R). That list already contains roxygen2 and covr, so I'd encourage you to submit a PR with covrpage.

I'm not aware of any list that maintains "style" packages. I'd encourage you to create a new subsection for awesome-R or start an entirely new list (please do let me know if you do either of these options; I'd be happy to advertise on Twitter so that people learn about the resource).

**Comment by yonicd** [comment]
@IndrajeetPatil https://github.com/qinwf/awesome-R/pull/167
